# site properties and page defaults
title: The Data Innovation Lab
subtitle: 
description: Established in July 2021, the Data Innovation Lab serves as an integrated environment for research in the area of innovation economics and management. We are particularly interested in understanding how we can leverage and comprehend the role of the data and AI revolution in shaping innovation, entrepreneurship and creativity at the individual, firm and societal level. 

For instance, our prior work has shown the [https://nagaraj.squarespace.com/publications-all/the-private-impact-of-public-data](impact of satellite imagery on discovery and entrepreneurship) in the gold mining industry, the [https://www.matteotranchero.com/pdf/Matteo_Tranchero_JMP_latest.pdf](impact of data-driven genomics on innovation) in the pharmaceutical industry, and the [https://www.abhishekn.com/publications-all/getting-on-the-map-the-impact-of-online-listings-on-business-performance](impact of online review listings on business performance) in the restaurant industry. Our research is typically conducted using large-scale observational data and applied microeconometric techniques, as well as applied machine learning tools, albeit complemented with in-depth phenomenological and qualitative work in the settings we study.

With chapters at the UC Berkeley Haas School of Business and the Wharton School of the University of Pennsylvania, we are a highly collaborative group. We host researchers at various stages of their careers, including pre-doctoral and post-doctoral scholars, PhD candidates, and undergraduate/master’s students. For more information, please click the links below.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@the-data-innovation-lab.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: the-data-innovation-lab
  twitter: the-data-innovation-lab
  youtube: the-data-innovation-lab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
